resources:
  - name: docker_Build_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: dockertest
      
  - name: docker_build_promote_test
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildNumber: 1
      buildName: dockertest
      
  - name: dockerbuild_vijay
    type: GitRepo
    configuration:
      path: vijayreddy1991/nativesteps
      gitProvider: vijay
      branches:
        include: docker
        
pipelines:
  - name: docker_vijay
    configuration: 
      runtime: # optional            
        type: host 
    steps:
      - name: dockerBuild
        type: DockerBuild
        configuration:
          affinityGroup: A
          dockerFileLocation: .
          dockerFileName: Dockerfile
#           dockerImageName: 'release1442.jfrogdev.org/docker-local/test'
#           dockerImageName: 'rhel8rt.jfrog-pipelines.com/docker-local/pipelines'
#           dockerImageName: 'pipelines.westus.cloudapp.azure.com:8082/docker-local/pipelines'
          dockerImageName: 'c7-install.jfrog-pipelines.com/docker-local/pipelines'
#           dockerImageName: 'dev.jfrog-pipelines.com/docker-local/pipelines'
          dockerImageTag: '${run_number}'
          integrations:
            - name: art_v
          inputResources:
            - name: dockerbuild_vijay
        execution:
          onStart:
            - echo "hi"
            - docker images
            - printenv
            - ls -la
          onSuccess:
            - docker images
      - name: dockerPush
        type: DockerPush
        configuration:
          affinityGroup: A
          targetRepository: docker-local
          integrations:
            - name: art_v
          inputSteps:
            - name: dockerBuild
            
#       - name: dockerPublish
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: dockerPush
#           outputResources:
#             - name: dockerbuild_vijay
            
#       - name: dockerPromote
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           inputSteps:
#             - name: dockerPublish
#           integrations:
#             - name: art_v
# #           inputResources:
# #             - name: dockerbuild_vijay
#           outputResources:
#             - name: docker_build_promote_vijay
            
            



            
            
