resources:
  - name: connecting_resource_vijay
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

#   - name: testfileSpec
#     type: FileSpec
#     configuration:     
#       sourceArtifactory: art_v
#       pattern: "test-generic-local/github.com/deepika/hello/@v/v0.0.0.mod"
#       buildName: go_test
#        buildNumber:          2387

  - name: ns_aql
    type: Aql
    configuration:
      sourceArtifactory: art_v
      query: 'items.find({"$and":[{"artifact.module.build.name":{"$eq":"native_pipeline"}},{"artifact.module.build.number":{"$eq":"8"}}]})'     
      #addedProperties:
      mappings:
        - name: "a"
          input: "regex"
          output: "$1/$2"
        - name: "b"
          input: "regex"
          output: "$2/$1"
      

  - name: ns_buildInfo_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_buildInfo
      buildNumber: 123

  
  - name: ns_promotedInfo_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_promotedInfo
      buildNumber: 1

  - name: artifactory_go_example
    type: GitRepo
    configuration:
      path: vijayreddy1991/project-examples
      branches:
        include: master
      gitProvider: git_v
  - name: artifactory_go_exampletest
    type: GitRepo
    configuration:
      path: vijayreddy1991/project-examples
      branches:
        include: master
      gitProvider: git_v

  - name: artifactory_go_module_example
    type: GitRepo
    configuration:
      path: vijayreddy1991/artifactory-go-example
      branches:
        include: master
      gitProvider: git_v

  - name: go_build_info_publish_moduletest
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_example_module_publish_varsha
      buildNumber: 332
      
  - name: go_build_info_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_example_build_publish_varsha
      buildNumber: 32
  
  - name: promoted_go_build_info_go_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: promote_go_build_info_publish
      buildNumber: 35

  - name: promoted_build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: promotoed-full-gradle-native
      buildNumber: 1

  - name: gradle_repo
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vijayreddy1991/project-examples

  - name: build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: full-gradle-native
      buildNumber: 1

  - name: mvnBuild_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: mvn_sample_build_master_test
      buildNumber: 9

  - name: mvnBuild_infoScaned
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: mvn_scan_master_test
      buildNumber: 2
      
  - name: mvnBuild_infopromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: mvn_promote_build_master_test
      buildNumber: 3
      
  - name: maven_repo
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vijayreddy1991/project-examples

  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: vijayreddy1991/npmHelloWorld
      gitProvider: git_v

  - name: npm_build_info_publish1
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: npm_publish
      buildNumber: 1

  - name: buildinfo_for_npmPublish
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: npm_publish
      buildNumber: 1
  
  - name: npm_build_info_promoted
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: npm+promote
      buildNumber: 1

  - name: git_vishnu
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vijayreddy1991/charts
pipelines:      
  - name: vijay_goBuildtest
#     configuration:
#       nodePool: 
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: golang-example/hello
          repository: test-go-local
          outputLocation: /tmp/dist
          outputFile: hello_sample
          inputResources:
            - name: artifactory_go_example
            - name: connecting_resource_vijay
          integrations:
            - name: art_v
#           inputSteps:
#             - name: Upload_to_artifactory
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: go
#                 versions:
#                   - "1.15.2-f2674"
        execution:
          onStart:
#             - "buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)"
#             - "pushd $buildDir/golang-example/hello"
#             - "go get -insecure"
#             - popd
            - Push-Location $res_artifactory_go_example_resourcePath/golang-example/hello
            - go get -insecure
            - Pop-Location
            - go version

      - name: publish_go_binarytest
        type: GoPublishBinary
        configuration:
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "go_test"
#             JFROG_CLI_BUILD_NUMBER: 2387
          inputSteps:
            - name: build_go
          targetRepository: test-go-local
          integrations:
            - name: art_v
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: go
#                 versions:
#                   - "1.15.2-f2674"
     
      - name: publish_buildtest
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binarytest
          outputResources:
            - name: go_build_info_publishtest
        
      - name: publish_go_moduletest
        type: GoPublishModule
        execution:
          onStart:
            - go version
        configuration:  
#           environmentVariables: # optional
#             JFROG_CLI_BUILD_NAME: "go_test"
#             JFROG_CLI_BUILD_NUMBER: 2387
          sourceLocation: .  # required
          version: v0.0.0           # required
          targetRepository: test-go-local
          autoPublishBuildInfo: true
          integrations:
            - name: art_v
#           runtime: 
#             type: image
#             image: 
#               auto:
#                 language: go
#                 versions:
#                   - "1.15.2-f2674"
          inputResources:
            - name: artifactory_go_module_example
          outputResources:
            - name: go_build_info_publish_moduletest
            
      - name: promote_build_gotest_binary
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: art_v
          inputResources:
            - name: go_build_info_publishtest #go_build_info_publish
          outputResources:
            - name: promoted_go_build_info_go_publishtest
    
      - name: promote_build_gotest_module
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: art_v
          inputResources:
            - name: go_build_info_publish_moduletest
          outputResources:
            - name: promoted_go_build_info_go_publishtest
      
