resources:
  - name: vijay_go_build_publish
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_example_build_publish_varsha
      buildNumber: 32
      
  - name: vijay_artifactory_go_module_example
    type: GitRepo
    configuration:
      path: vijayreddy1991/artifactory-go-example
      branches:
        include: master
      gitProvider: vijay
  - name: go_build_info_publish_moduletest
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_example_module_publish_varsha
      buildNumber: 332
  - name: promoted_go_build_info_go_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: promote_go_build_info_publish
      buildNumber: 35
  - name: artifactory_go_exampletest
    type: GitRepo
    configuration:
      path: vijayreddy1991/project-examples
      branches:
        include: master
      gitProvider: vijay
      
pipelines:      
  - name: vijay_goBuildtest
#     configuration:
#       nodePool: 
    steps:
      - name: build_gotest
        type: GoBuild
        configuration:
          sourceLocation: golang-example/hello
          repository: test-go-local
          outputLocation: /tmp/dist
          outputFile: go-app
          goCommand: build -o /tmp/vijay/go-app
          inputResources:
            - name: artifactory_go_exampletest
          integrations:
            - name: art_v
        execution:
          onStart:
            - go version
            
      - name: publish_go_binarytest
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_gotest
          targetRepository: test-go-local
          integrations:
            - name: art_v
            
#       - name: publish_buildtest
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: publish_go_binarytest
#           outputResources:
#             - name: vijay_go_build_publish
            
#       - name: publish_go_moduletest
#         type: GoPublishModule
#         execution:
#           onStart:
#             - go version
#         configuration:
#           sourceLocation: .
#           version: v0.0.0
#           targetRepository: test-go-local
#           autoPublishBuildInfo: true
#           integrations:
#             - name: vijay_art
#           inputResources:
#             - name: vijay_artifactory_go_module_example
#           outputResources:
#             - name: go_build_info_publish_moduletest
            
#       - name: promote_build_gotest_binary
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           integrations:
#             - name: vijay_art
#           inputResources:
#             - name: vijay_go_build_publish
#           outputResources:
#             - name: promoted_go_build_info_go_publishtest

#       - name: promote_build_gotest_module
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           integrations:
#             - name: vijay_art
#           inputResources:
#             - name: go_build_info_publish_moduletest
#           outputResources:
#             - name: promoted_go_build_info_go_publishtest     

#       - name: build_go
#         type: GoBuild
#         configuration:
#           sourceLocation: golang-example/hello
#           repository: test-go-local
#           outputLocation: /tmp/dist
#           outputFile: hello_sample
#           inputResources:
#             - name: artifactory_go_example
#             - name: connecting_resource_vijay
#           integrations:
#             - name: art_v
# #           inputSteps:
# #             - name: Upload_to_artifactory
# #           runtime: 
# #             type: image
# #             image: 
# #               auto:
# #                 language: go
# #                 versions:
# #                   - "1.15.2-f2674"
#         execution:
#           onStart:
# #             - "buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)"
# #             - "pushd $buildDir/golang-example/hello"
# #             - "go get -insecure"
# #             - popd
#             - Push-Location $res_artifactory_go_example_resourcePath/golang-example/hello
#             - go get -insecure
#             - Pop-Location
#             - go version

#       - name: publish_go_binarytest
#         type: GoPublishBinary
#         configuration:
# #           environmentVariables: # optional
# #             JFROG_CLI_BUILD_NAME: "go_test"
# #             JFROG_CLI_BUILD_NUMBER: 2387
#           inputSteps:
#             - name: build_go
#           targetRepository: test-go-local
#           integrations:
#             - name: art_v
# #           runtime: 
# #             type: image
# #             image: 
# #               auto:
# #                 language: go
# #                 versions:
# #                   - "1.15.2-f2674"
     
#       - name: publish_buildtest
#         type: PublishBuildInfo
#         configuration:
#           inputSteps:
#             - name: publish_go_binarytest
#           outputResources:
#             - name: go_build_info_publishtest
        
#       - name: publish_go_moduletest
#         type: GoPublishModule
#         execution:
#           onStart:
#             - go version
#         configuration:  
# #           environmentVariables: # optional
# #             JFROG_CLI_BUILD_NAME: "go_test"
# #             JFROG_CLI_BUILD_NUMBER: 2387
#           sourceLocation: .  # required
#           version: v0.0.0           # required
#           targetRepository: test-go-local
#           autoPublishBuildInfo: true
#           integrations:
#             - name: art_v
# #           runtime: 
# #             type: image
# #             image: 
# #               auto:
# #                 language: go
# #                 versions:
# #                   - "1.15.2-f2674"
#           inputResources:
#             - name: artifactory_go_module_example
#           outputResources:
#             - name: go_build_info_publish_moduletest
            
#       - name: promote_build_gotest_binary
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           integrations:
#             - name: art_v
#           inputResources:
#             - name: go_build_info_publishtest #go_build_info_publish
#           outputResources:
#             - name: promoted_go_build_info_go_publishtest
    
#       - name: promote_build_gotest_module
#         type: PromoteBuild
#         configuration:
#           targetRepository: test-generic-local
#           integrations:
#             - name: art_v
#           inputResources:
#             - name: go_build_info_publish_moduletest
#           outputResources:
#             - name: promoted_go_build_info_go_publishtest
      
