resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/charts
   
  - name: helm_repo_vijay
    type: HelmChart
    configuration: 
      sourceArtifactory: art_v
      repository: helm-local
      chart: test
      version: 1.0.0

pipelines:
  - name: test_helm_vijay

    steps:
      - name: helm_publish
        type: HelmPublish
        configuration:
          chartPath: stable/tomcat
 
          inputResources:
            - name: git_vijay                    
          outputResources:
            - name: helm_repo_vijay                  # required
 
        execution:
          onStart:
            - echo "Preparing for work..."
            - printenv
          onSuccess:
            - echo "Job well done!"
            - printenv
          onFailure:
            - echo "uh oh, something went wrong"
            - printenv
          onComplete: #always
            - echo "Cleaning up some stuff"
            - printenv
