resources:
  - name: mavenBuild_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: mvn_sample_build_vijay
      buildNumber: 9
  - name: mavenBuild_infopromote_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: mvn_promote_build_vijay
      buildNumber: 3
  - name: maven_repo_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/project-examples
      
pipelines:
  - name: vijay_mvn_test
    steps:
      - name: mvnBuild_sample
        type: MvnBuild
        configuration:
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: maven_repo_vijay
          integrations:
            - name: art_v
        execution:
          onStart:
            - javac -version
            - mvn --version
      - name: mvnBuild_publishs
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: mvnBuild_sample
          outputResources:
            - name: mavenBuild_vijay
      - name: mvn_build_promote
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          includeDependencies: true
#           status: promote success
#           comment: >-
#             maven build should be promoted from varsha-local. maven build should be
#             promoted from varsha-local. maven build should be promoted from
#             varsha-local. maven build should be promoted from varsha-local
          copy: true
          inputResources:
            - name: mavenBuild_vijay
          outputResources:
            - name: mavenBuild_infopromote_vijay
