resources:
  - name: npmHelloWorld_vijay
    type: GitRepo
    configuration:
      path: vijayreddy1991/npmHelloWorld
      gitProvider: vijay
  - name: npm_build_info_publish_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: npm_publish
      buildNumber: 1
  - name: npm_build_info_promote_vijay
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: npm+promote
      buildNumber: 1
      
      
pipelines:
  - name: npm_vijay
#     configuration:
#       nodePool: win_2019
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_vijay
          integrations:
            - name: art_v
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-virtual
          inputSteps:
            - name: build_npm
          integrations:
            - name: art_v
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          outputResources:
            - name: npm_build_info_publish_vijay
      - name: build_npm_remote
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_vijay
          integrations:
            - name: art_v
      - name: publish_npm_auto_true
        type: NpmPublish
        configuration:
          repositoryName: npm-virtual
          autoPublishBuildInfo: true
          inputSteps:
            - name: build_npm_remote
          outputResources:
            - name: npm_build_info_publish_vijay
          integrations:
            - name: art_v
      - name: promote_build_npm
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: art_v
          inputResources:
            - name: npm_build_info_publish_vijay
          outputResources:
            - name: npm_build_info_promote_vijay
